name: Generate DOCX with Pandoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get repository name
      run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

    - name: Install Specific Version of Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/jgm/pandoc/releases/download/2.11.4/pandoc-2.11.4-1-amd64.deb
        sudo dpkg -i pandoc-2.11.4-1-amd64.deb

    - name: Install Fonts
      run: |
        sudo apt-get install -y fonts-dejavu fonts-liberation
        # Add any other fonts you need here

    - name: Generate DOCX
      run: pandoc -s --toc --toc-depth=3 --metadata title="${{ env.REPO_NAME }}" --metadata author="Author" -o ${{ env.REPO_NAME }}.docx --reference-doc=template.docx $(cat book-order.txt)

    - name: Upload DOCX as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.REPO_NAME }}.docx
        path: ${{ env.REPO_NAME }}.docx
